# Generated by Django 3.2.5 on 2021-07-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardly', '0003_auto_20210711_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
